### ISSUE TITLE
make编译出错

### ISSUE THREAD

**Issue by incredibleeeeee** [three-water666/MiniC#1]
->mingw32-make.exe
make clean
process_begin: CreateProcess(NULL, make clean, ...) failed.
make (e=2): 系统找不到指定的文件。
mingw32-make: *** [makefile:4: all] Error 2

**Comment by three-water666** [comment]
可以试试先执行make prepare再执行 make minic 。

**Comment by three-water666** [comment]
可以试试先执行make prepare再执行 make minic 。

**Comment by incredibleeeeee** [comment]
linux下执行./minic test.c
打印一串*
***********************************************************************************

**Comment by three-water666** [comment]
是不是路径不对，应该是./minic ./test/test.c

**Comment by incredibleeeeee** [comment]
不是，已经拷贝到同目录了，而且如果找不到文件会提示不是输出一串*

**Comment by incredibleeeeee** [comment]
好像是你把代码注释了，我先看看

**Comment by incredibleeeeee** [comment]
大佬能把你的文法也发一下吗，我对比改一下

**Comment by three-water666** [comment]
文法刚刚上传了

**Comment by incredibleeeeee** [comment]
好
